export const FETCH_GIF = "FETCH_GIF";
export const FETCH_GIF_FULFILLED = "FETCH_GIF_FULFILLED";
export const FETCH_GIF_FAIL = "FETCH_GIF_FAIL";

export const FETCH_RANDOM_GIF = "FETCH_RANDOM_GIF";
export const FETCH_RANDOM_GIF_FULFILLED = "FETCH_RANDOM_GIF_FULFILLED";
export const FETCH_RANDOM_GIF_FAIL = "FETCH_RANDOM_GIF_FAIL";
